// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARUYYBWxbM11x5ep4PG6pxH5wWHkN9qCU',
    appId: '1:622034531752:web:1fabf47ecaf6d6af7e199d',
    messagingSenderId: '622034531752',
    projectId: 'e-book-store-b0bb0',
    authDomain: 'e-book-store-b0bb0.firebaseapp.com',
    storageBucket: 'e-book-store-b0bb0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz5v7SpYFa-2JDPqwZ69m843g5JXK5xQo',
    appId: '1:622034531752:android:3d700e4db6c948b37e199d',
    messagingSenderId: '622034531752',
    projectId: 'e-book-store-b0bb0',
    storageBucket: 'e-book-store-b0bb0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdHd53oez8N3sjpl7C8nq9pMt9-VsU-84',
    appId: '1:622034531752:ios:7a7508108c2f422a7e199d',
    messagingSenderId: '622034531752',
    projectId: 'e-book-store-b0bb0',
    storageBucket: 'e-book-store-b0bb0.appspot.com',
    iosBundleId: 'com.example.eBook2023',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdHd53oez8N3sjpl7C8nq9pMt9-VsU-84',
    appId: '1:622034531752:ios:dd31c9cad45318707e199d',
    messagingSenderId: '622034531752',
    projectId: 'e-book-store-b0bb0',
    storageBucket: 'e-book-store-b0bb0.appspot.com',
    iosBundleId: 'com.example.eBook2023.RunnerTests',
  );
}
